# Generated by Django 3.0.8 on 2020-10-12 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='items',
        ),
        migrations.AddField(
            model_name='companydetails',
            name='image',
            field=models.ImageField(default='default_company_logo.png', upload_to='company_logo'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default_product_logo.png', upload_to='product_images'),
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('product_cost', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('total', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Transaction')),
            ],
        ),
    ]
