# Generated by Django 3.0.8 on 2020-10-13 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201012_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionitem',
            name='product_cost',
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='product_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=1000),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=1000),
        ),
    ]
