# Generated by Django 3.0.8 on 2020-10-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201013_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('glass', 'g')], default='box', max_length=100),
        ),
    ]
