# Generated by Django 3.0.8 on 2020-10-21 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201021_0947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdata',
            options={'ordering': ['-date']},
        ),
    ]
