# Generated by Django 3.0.8 on 2020-10-21 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201021_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
