# Generated by Django 3.0.8 on 2020-10-22 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201021_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdata',
            options={'ordering': ['-date', 'product']},
        ),
    ]
