# Generated by Django 3.0.8 on 2020-10-28 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201024_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minimumproduct',
            name='company',
        ),
        migrations.DeleteModel(
            name='MaximumProduct',
        ),
        migrations.DeleteModel(
            name='MinimumProduct',
        ),
    ]
