# Generated by Django 3.1.7 on 2021-04-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20201109_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='image',
            field=models.ImageField(default='default_company_logo.png', upload_to='company_logo'),
        ),
    ]
