# Generated by Django 3.1.7 on 2021-09-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210402_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetails',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='costrevenueanalysis',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit_cost',
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='image',
            field=models.ImageField(default='default_company_logo.png', upload_to='company_logo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(default='box', max_length=100),
        ),
    ]
