# Generated by Django 3.2.8 on 2021-10-06 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210926_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costrevenueanalysis',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.companydetails'),
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.companydetails'),
        ),
        migrations.AlterField(
            model_name='productdata',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.companydetails'),
        ),
        migrations.AlterField(
            model_name='stockoverview',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.companydetails'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.companydetails'),
        ),
    ]
