# Generated by Django 3.1.7 on 2021-10-14 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20211006_1503'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CostRevenueAnalysis',
            new_name='RevenueAnalysis',
        ),
    ]
